<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $products = [
            [
                'category_id' => '3',
                'title'=> 'Zoom Meeting Harian 100 Partisipan',
                'slug' => 'zoom-meeting-harian-100-partisipan',
                'image' => '',
                'package'=> 'Harian',
                'benefit' => '100 Partisipan',
                'price'=> '15000',
                'description' => 'lorem ipsum',
                'name_profil'=> 'Randa',
                'bio_profil' => 'Saya adalah freelancer event organizer berpengalaman sejak 2020. Sebagai Freelancer selama kurang lebih 3 tahun, saya betul-betul dapat memahami kebutuhan client.',
                'fb_profil'=> '-',
                'ig_profil' => '-',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'category_id' => '3',
                'title'=> 'Zoom Meeting Harian 300 Partisipan',
                'slug' => 'zoom-meeting-harian-300-partisipan',
                'image' => '',
                'package'=> 'Harian',
                'benefit' => '300 Partisipan',
                'price'=> '36000',
                'description' => 'lorem ipsum',
                'name_profil'=> 'Randa',
                'bio_profil' => 'Saya adalah freelancer event organizer berpengalaman sejak 2020. Sebagai Freelancer selama kurang lebih 3 tahun, saya betul-betul dapat memahami kebutuhan client.',
                'fb_profil'=> '-',
                'ig_profil' => '-',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'category_id' => '3',
                'title'=> 'Zoom Meeting Harian 500 Partisipan',
                'slug' => 'zoom-meeting-harian-500-partisipan',
                'image' => '',
                'package'=> 'Harian',
                'benefit' => '500 Partisipan',
                'price'=> '10000',
                'description' => 'lorem ipsum',
                'name_profil'=> 'Randa',
                'bio_profil' => 'Saya adalah freelancer event organizer berpengalaman sejak 2020. Sebagai Freelancer selama kurang lebih 3 tahun, saya betul-betul dapat memahami kebutuhan client.',
                'fb_profil'=> '-',
                'ig_profil' => '-',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'category_id' => '3',
                'title'=> 'Zoom Meeting Harian 1000 Partisipan',
                'slug' => 'zoom-meeting-harian-1000-partisipan',
                'image' => '',
                'package'=> 'Harian',
                'benefit' => '1000 Partisipan',
                'price'=> '150000',
                'description' => 'lorem ipsum',
                'name_profil'=> 'Randa',
                'bio_profil' => 'Saya adalah freelancer event organizer berpengalaman sejak 2020. Sebagai Freelancer selama kurang lebih 3 tahun, saya betul-betul dapat memahami kebutuhan client.',
                'fb_profil'=> '-',
                'ig_profil' => '-',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'category_id' => '3',
                'title'=> 'Zoom Meeting Pro 1 Bulan 100 Partisipan',
                'slug' => 'zoom-meeting-pro-satubulan-100-partisipan',
                'image' => '',
                'package'=> 'Pro 1 Bulan',
                'benefit' => '100 Partisipan',
                'price'=> '95000',
                'description' => 'lorem ipsum',
                'name_profil'=> 'Randa',
                'bio_profil' => 'Saya adalah freelancer event organizer berpengalaman sejak 2020. Sebagai Freelancer selama kurang lebih 3 tahun, saya betul-betul dapat memahami kebutuhan client.',
                'fb_profil'=> '-',
                'ig_profil' => '-',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'category_id' => '3',
                'title'=> 'Zoom Meeting Pro 1 Bulan 300 Partisipan',
                'slug' => 'zoom-meeting-pro-satubulan-300-partisipan',
                'image' => '',
                'package'=> 'Pro 1 Bulan',
                'benefit' => '300 Partisipan',
                'price'=> '260000',
                'description' => 'lorem ipsum',
                'name_profil'=> 'Randa',
                'bio_profil' => 'Saya adalah freelancer event organizer berpengalaman sejak 2020. Sebagai Freelancer selama kurang lebih 3 tahun, saya betul-betul dapat memahami kebutuhan client.',
                'fb_profil'=> '-',
                'ig_profil' => '-',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'category_id' => '3',
                'title'=> 'Zoom Meeting Pro 1 Bulan 500 Partisipan',
                'slug' => 'zoom-meeting-pro-satubulan-500-partisipan',
                'image' => '',
                'package'=> 'Pro 1 Bulan',
                'benefit' => '500 Partisipan',
                'price'=> '350000',
                'description' => 'lorem ipsum',
                'name_profil'=> 'Randa',
                'bio_profil' => 'Saya adalah freelancer event organizer berpengalaman sejak 2020. Sebagai Freelancer selama kurang lebih 3 tahun, saya betul-betul dapat memahami kebutuhan client.',
                'fb_profil'=> '-',
                'ig_profil' => '-',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'category_id' => '3',
                'title'=> 'Zoom Meeting Pro 1 Bulan 1000 Partisipan',
                'slug' => 'zoom-meeting-pro-satubulan-1000-partisipan',
                'image' => '',
                'package'=> 'Pro 1 Bulan',
                'benefit' => '1000 Partisipan',
                'price'=> '550000',
                'description' => 'lorem ipsum',
                'name_profil'=> 'Randa',
                'bio_profil' => 'Saya adalah freelancer event organizer berpengalaman sejak 2020. Sebagai Freelancer selama kurang lebih 3 tahun, saya betul-betul dapat memahami kebutuhan client.',
                'fb_profil'=> '-',
                'ig_profil' => '-',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'category_id' => '3',
                'title'=> 'Zoom Meeting Education 1 Bulan 100 Partisipan',
                'slug' => 'zoom-meeting-edu-satubulan-100-partisipan',
                'image' => '',
                'package'=> 'Education 1 Bulan',
                'benefit' => '100 Partisipan',
                'price'=> '70000',
                'description' => 'lorem ipsum',
                'name_profil'=> 'Randa',
                'bio_profil' => 'Saya adalah freelancer event organizer berpengalaman sejak 2020. Sebagai Freelancer selama kurang lebih 3 tahun, saya betul-betul dapat memahami kebutuhan client.',
                'fb_profil'=> '-',
                'ig_profil' => '-',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'category_id' => '3',
                'title'=> 'Zoom Meeting Education 1 Bulan 300 Partisipan',
                'slug' => 'zoom-meeting-edu-satubulan-300-partisipan',
                'image' => '',
                'package'=> 'Education 1 Bulan',
                'benefit' => '300 Partisipan',
                'price'=> '200000',
                'description' => 'lorem ipsum',
                'name_profil'=> 'Randa',
                'bio_profil' => 'Saya adalah freelancer event organizer berpengalaman sejak 2020. Sebagai Freelancer selama kurang lebih 3 tahun, saya betul-betul dapat memahami kebutuhan client.',
                'fb_profil'=> '-',
                'ig_profil' => '-',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'category_id' => '3',
                'title'=> 'Zoom Meeting Pro 1 Tahun 100 Partisipan',
                'slug' => 'zoom-meeting-pro-satutahun-100-partisipan',
                'image' => '',
                'package'=> 'Pro 1 Bulan',
                'benefit' => '100 Partisipan',
                'price'=> '800000',
                'description' => 'lorem ipsum',
                'name_profil'=> 'Randa',
                'bio_profil' => 'Saya adalah freelancer event organizer berpengalaman sejak 2020. Sebagai Freelancer selama kurang lebih 3 tahun, saya betul-betul dapat memahami kebutuhan client.',
                'fb_profil'=> '-',
                'ig_profil' => '-',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'category_id' => '3',
                'title'=> 'Zoom Meeting Pro 1 Tahun 300 Partisipan',
                'slug' => 'zoom-meeting-pro-satutahun-300-partisipan',
                'image' => '',
                'package'=> 'Pro 1 Tahun',
                'benefit' => '300 Partisipan',
                'price'=> '2800000',
                'description' => 'lorem ipsum',
                'name_profil'=> 'Randa',
                'bio_profil' => 'Saya adalah freelancer event organizer berpengalaman sejak 2020. Sebagai Freelancer selama kurang lebih 3 tahun, saya betul-betul dapat memahami kebutuhan client.',
                'fb_profil'=> '-',
                'ig_profil' => '-',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'category_id' => '3',
                'title'=> 'Zoom Meeting Pro 1 Tahun 500 Partisipan',
                'slug' => 'zoom-meeting-pro-satutahun-500-partisipan',
                'image' => '',
                'package'=> 'Pro 1 Tahun',
                'benefit' => '500 Partisipan',
                'price'=> '3300000',
                'description' => 'lorem ipsum',
                'name_profil'=> 'Randa',
                'bio_profil' => 'Saya adalah freelancer event organizer berpengalaman sejak 2020. Sebagai Freelancer selama kurang lebih 3 tahun, saya betul-betul dapat memahami kebutuhan client.',
                'fb_profil'=> '-',
                'ig_profil' => '-',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'category_id' => '3',
                'title'=> 'Zoom Meeting Pro 1 Tahun 1000 Partisipan',
                'slug' => 'zoom-meeting-pro-satutahun-1000-partisipan',
                'image' => '',
                'package'=> 'Pro 1 Tahun',
                'benefit' => '1000 Partisipan',
                'price'=> '4500000',
                'description' => 'lorem ipsum',
                'name_profil'=> 'Randa',
                'bio_profil' => 'Saya adalah freelancer event organizer berpengalaman sejak 2020. Sebagai Freelancer selama kurang lebih 3 tahun, saya betul-betul dapat memahami kebutuhan client.',
                'fb_profil'=> '-',
                'ig_profil' => '-',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'category_id' => '1',
                'title'=> 'Desain Poster',
                'slug' => 'desain-poster',
                'image' => '',
                'package'=> 'Premium',
                'benefit' => 'Revisi Sepuasnya',
                'price'=> '55000',
                'description' => 'lorem ipsum',
                'name_profil'=> 'Ihsan Haryansyah',
                'bio_profil' => 'Saya adalah freelancer berpengalaman sejak 2018. Sebagai Freelancer selama kurang lebih 3 tahun, saya betul-betul dapat memahami kebutuhan client.',
                'fb_profil'=> '-',
                'ig_profil' => '-',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'category_id' => '2',
                'title'=> 'Web App Developer',
                'slug' => 'web-app-developer',
                'image' => '',
                'package'=> 'Standart',
                'benefit' => 'Bebas Biaya Maintenance Selama 1 Tahun',
                'price'=> '1000000',
                'description' => 'lorem ipsum',
                'name_profil'=> 'Ihsan Haryansyah',
                'bio_profil' => 'Saya adalah freelancer Web Design & Web Development berpengalaman sejak 2018. Sebagai Freelancer web design & pengembang web berbasis laravel selama kurang lebih 3 tahun, saya betul-betul dapat memahami kebutuhan client.',
                'fb_profil'=> '-',
                'ig_profil' => '-',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'category_id' => '2',
                'title'=> 'Archgis Web',
                'slug' => 'archgis-web',
                'image' => '',
                'package'=> 'Standart',
                'benefit' => 'Bebas Biaya Maintenance Selama 1 Tahun',
                'price'=> '1500000',
                'description' => 'lorem ipsum',
                'name_profil'=> 'Ihsan Haryansyah',
                'bio_profil' => 'Saya adalah freelancer Web Design & Web Development berpengalaman sejak 2018. Sebagai Freelancer web design & pengembang web berbasis laravel selama kurang lebih 3 tahun, saya betul-betul dapat memahami kebutuhan client.',
                'fb_profil'=> '-',
                'ig_profil' => '-',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
        ];
        
        Product::insert($products);
    }
}
